AWSTemplateFormatVersion: 2010-09-09
Parameters:
  CFNJobName:
    Type: String
    Default: File-to-File
  CFNIAMRoleName:
    Type: String
  CFNScriptLocation:
    Type: String
    Default: s3://glue-scripts-etljobs/FileToFile.scala
  CFNExtraJars:
    Type: String
Resources:
  FileToFileJob:
    Type: 'AWS::Glue::Job'
    Properties:
      Role: !Ref CFNIAMRoleName
      DefaultArguments:
        "--job-language": scala
        "--class": etljobs.scripts.FileToFile
        "--TempDir": s3://glue-scripts-etljobs/temp
        "--enable-continuous-cloudwatch-log": true
        "--extra-jars": !Ref CFNExtraJars
        "--job-bookmark-option": job-bookmark-disable
        "--enable-glue-datacatalog": ''
        "--iam-role": !Ref CFNIAMRoleName
        "--fs.s3a.endpoint": 's3.eu-central-1.amazonaws.com'
        "--input-bucket": 's3a://input-data-etljobs'
        "--output-bucket": 's3a://raw-data-etljobs'
        "--schema-bucket": 's3a://schema-etljobs'
      MaxRetries: 0
      Description: Job created with CloudFormation
      Command:
        Name: glueetl
        ScriptLocation: !Ref CFNScriptLocation
      AllocatedCapacity: 2
      ExecutionProperty:
        MaxConcurrentRuns: 1
      GlueVersion: '3.0'
      Name: !Ref CFNJobName